from app.models.tickets_model import Ticket
from app.models.attachments_model import Attachment
from app.models.user_model import User
from app.models.categories_model import Category
from app.models.departments_model import Department
from app.models.messages_model import Message  
from app.models.ticket_assigned_user_model import TicketAssignedUser
from app.models.category_department_model import CategoryDepartment
from app.models.user_model import update_fields
